// Generated by CoffeeScript 1.7.1
(function() {
  var arrInput, drawOneTri, drawRow, drawTri, input, length, output, times;

  input = "2 3 2 5 3";

  output = new Array();

  arrInput = input.split(' ');

  times = arrInput[0];

  length = arrInput.length;

  drawRow = function(v1) {
    var intTimes, rowItem;
    rowItem = "";
    intTimes = v1;
    while (intTimes--) {
      rowItem += v1.toString();
    }
    return rowItem;
  };

  drawOneTri = function(v1) {
    var arrTri, index;
    arrTri = new Array((v1 - 1) * 2 + 1);
    index = 0;
    while (index < v1) {
      arrTri[(v1 - 1) - index] = arrTri[(v1 - 1) + index] = drawRow(v1 - index);
      index++;
    }
    return arrTri.join("\n");
  };

  drawTri = function(v1, v2) {
    var arrTri;
    arrTri = new Array();
    while (v1--) {
      arrTri.push(drawOneTri(v2));
    }
    return arrTri.join("\n\n");
  };

  while (times > 0) {
    output.push(drawTri(arrInput[(length / 2 - times) * 2 + 1], arrInput[(length / 2 - times) * 2]));
    times--;
  }

  alert(output.join("\n\n"));

}).call(this);
